### ISSUE TITLE
Start up error! 1.1.8 just upgraded from 1.1.7

### ISSUE THREAD

**Issue by ApolloX939** [CameronRedmore/Amethyst-Cache-Compactor#4]
I got:

`[20:09:59 ERROR]: Error occurred while enabling AmethystCacheCompactor v1.1.8 (Is it up to date?)
java.lang.NoSuchFieldError: MUSIC_DISC_MALL
	at uk.co.amethystdevelopment.acc.backend.ACC_DIR.getItem(ACC_DIR.java:178) ~[?:?]
	at uk.co.amethystdevelopment.acc.AmethystCacheCompactor.onEnable(AmethystCacheCompactor.java:53) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.jar:git-Paper-1143]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.jar:git-Paper-1143]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1143]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [patched_1.12.jar:git-Paper-1143]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12.jar:git-Paper-1143]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched_1.12.jar:git-Paper-1143]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched_1.12.jar:git-Paper-1143]
 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched_1.12.jar:git-Paper-1143]
 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.jar:git-Paper-1143]
 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1143]
 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
`

Please fix this, I did some digging thru the code I think where you have 
"Material.MUSIC_DISC_MALL" should be "Material.RECORD_MALL" (In ACC_DIR)
as there is no such thing as a music_disc_mall item in Minecraft. I ran 1.1.7 with no issues and got a notice that 1.1.8 was out, so I decided to update and I got this.

At first I thought the 1.1.7 database etc... was not compatible with 1.1.8 but I even moved the old directory so it would make everything new it still threw that error. (Take your time fixing this but please fix it, and if you need anymore information on what all I have running just let me know, I will try to respond as soon as possible)

Happy bug hunting.

**Comment by ApolloX939** [comment]
Well until you can get it working I will go back to using 1.1.7 on my 1.12 Minecraft Bukkit server, again if you need any further information about my server, such as what other plugins am I using feel free to ask.

**Comment by CameronRedmore** [comment]
Hi there,

Thanks for your issue. This is because the material was actually changed in 1.13 to use MUSIC_DISC_MALL rather than RECORD_MALL (which was used on 1.12). I'll need to implement some kind of method to change which is used in which version of Bukkit.

**Comment by ApolloX939** [comment]
Oh do you need that version? (Well I guess I will just add it to the end of this message) I used AE on my forge client but never wanted my server to be forge, so when I saw this plugin I instantly liked it, and I like the 1.1.8 config, looks like you added it so you could A: make your own recipe and B: you can change the storage on discs... (Kinda sorry for the wait, forgot to check about it)

Well it looks like I have Paper (Both Spigot and Bukkit)
Paper version is 1143 (API version 1.12-R0.1-SNAPSHOT)

Best luck.

**Comment by ApolloX939** [comment]
Of course, you might have meant that you were going to try to add some code to check that without me needing to send anything... :) As I like to say, "Better to send too much information than not enough".

**Comment by Beanzilla** [comment]
I will also see if I can spin up a 1.13 server just to check it isn't my side, well not completely.

**Comment by CameronRedmore** [comment]
Yeah, I was intending to write some code to check that haha. Thanks for the information anyway though!

I don't have any time to do anything through the week, so I won't be able to do anything until Saturday but then I'll look into what to do about this.

**Comment by ApolloX939** [comment]
Hey, I am glad to wait, just not wait a year for it... and I am glad to at least bring up this issue, I am sure there is some other person who runs a old server like I do.

**Comment by ApolloX939** [comment]
I know you may be quite busy working on making it for newer versions but just wanted to know where my issue is at, as far as getting it backwards compatible with older versions of Minecraft.

Thank you for a awesome plugin anyway! :)
